#include <exception>

int main(){
    throw std::runtime_error("Illegal!");
}
